# GLOBAL VARIABLES
remote_user: ezekiel

# elasticsearch vars
es_centos_rpm: elasticsearch.repo

# MYSQL
mysql_root_password: password123
app_user: ezekiel
http_host: ezekiel 
http_conf: ezekiel.conf
http_port: 80
disable_default: true

src: prometheus.service

# influxdb repo
influxdb_repo: influxdb.repo

# grafana repo
grafana_repo: grafana.repo

# Logstash conf
logstash_conf: logstash.conf

# Prometheus
prometheus_src: prometheus.service

# Nagios User and Pass
nagios_user: nagiosadmin
nagios_pass: 1234

# LAMP Variables
domain: ezekiel
owner: ezekiel
group: ezekiel
index_html: index.html
ubuntu_src: ezekiel-ubuntu.conf
centos_src: ezekiel-centos.conf
