---
- name: Adding Elasticsearch PGP Key in CentOS
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Copy RPM Repository to Remote in CentOS
  copy:
    src: "{{ es_centos_rpm }}"
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"

- name: Install elastic search in CentOS
  import_role:
    name: centospkg
  vars:
    package: elasticsearch

- name: Uncomment network.host

  replace:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#network.host.*'
    replace: 'network.host: localhost'

- name: Uncomment http.port
  replace:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#http.port.*'
    replace: 'http.port: 9200'

- name: Start and enable Elastic Search in CentOS
  service:
    name: elasticsearch
    state: started
    enabled: yes
